### ISSUE TITLE
error runnung serve:dist

### ISSUE THREAD

**Issue by shomy13** [akveo/blur-admin#108]
gulp-inject 1 files into auth.html.
path.js:7
    throw new TypeError('Path must be a string. Received ' + inspect(path));
    ^

TypeError: Path must be a string. Received undefined
    at assertPath (path.js:7:11)
    at Object.dirname (path.js:697:5)
    at C:\..\blur-admin-mint\node_modules\clean-css\lib\utils\input-source-map-tracker.js:191:56
    at Array.forEach (native)
    at trackContentSources (C:\..\blur-admin-mint\node_modules\clean-css\lib\utils\input-source-map-tracker.js:188:20)
    at InputSourceMapStore.trackLoaded (C:\..\blur-admin-mint\node_modules\clean-css\lib\utils\input-source-map-tracker.js:255:3)
    at fromString (C:\..\blur-admin-mint\node_modules\clean-css\lib\utils\input-source-map-tracker.js:32:8)
    at InputSourceMapStore.track (C:\..\blur-admin-mint\node_modules\clean-css\lib\utils\input-source-map-tracker.js:236:5)
    at C:\..\blur-admin-mint\node_modules\clean-css\lib\clean.js:145:44
    at CleanCSS.minify (C:\..\blur-admin-mint\node_modules\clean-css\lib\clean.js:127:42)

what could it be?

**Comment by shomy13** [comment]
npm install clean-css solved the problem.
