### ISSUE TITLE
gulp return error on 

### ISSUE THREAD

**Issue by ajkurt** [akveo/blur-admin#13]
I’m having problems to run gulp to build sources inside the extracted folder and someone can help me to solve it.
I already have run “npm install” having just some warnings, but the gulp return error on the config-validator.js. I can’t figure out how to fix it.

    [root@XX XXXXX blur-admin-master]# /usr/local/bin/gulp
    [13:54:32] Using gulpfile /usr/local/blur-admin-master/gulpfile.js
    [13:54:32] Starting 'clean'...
    [13:54:32] Finished 'clean' after 26 ms
    [13:54:32] Starting 'default'...
    [13:54:32] Starting 'scripts'...
    [13:54:32] Starting 'styles'...
    [13:54:33] Starting 'stylesAuth'...
    [13:54:33] Starting 'styles404'...
    [13:54:33] Starting 'copyVendorImages'...
    [13:54:33] Starting 'partials'...
    [13:54:33] Starting 'fonts'...
    [13:54:33] Finished 'default' after 379 ms
    [13:54:33] Finished 'fonts' after 36 ms
    [13:54:33] Finished 'copyVendorImages' after 87 ms
    [13:54:33] Starting 'other'...
    /usr/local/blur-admin-master/node_modules/eslint/lib/config/config-validator.js:102
        throw new Error(message.join(""));
        ^

    Error: /usr/local/.eslintrc:
        Configuration for rule "comma-dangle" is invalid:
        Value "only-multiline" must be an enum value.

    at validateRuleOptions (/usr/local/blur-admin-master/node_modules/eslint/lib/config/config-validator.js:102:8)
    at /usr/local/blur-admin-master/node_modules/eslint/lib/config/config-validator.js:148:13
    at Array.forEach (native)
    at Object.validate (/usr/local/blur-admin-master/node_modules/eslint/lib/config/config-validator.js:147:35)
    at Object.load (/usr/local/blur-admin-master/node_modules/eslint/lib/config/config-file.js:390:19)
    at loadConfig (/usr/local/blur-admin-master/node_modules/eslint/lib/config.js:74:33)
    at getLocalConfig (/usr/local/blur-admin-master/node_modules/eslint/lib/config.js:177:23)
    at Config.getConfig (/usr/local/blur-admin-master/node_modules/eslint/lib/config.js:272:22)
    at processText (/usr/local/blur-admin-master/node_modules/eslint/lib/cli-engine.js:203:27)
    at CLIEngine.executeOnText (/usr/local/blur-admin-master/node_modules/eslint/lib/cli-engine.js:686:26)
    [root@XXXXXXX blur-admin-master]#

I appreciate the attention

**Comment by lugovsky** [comment]
Loooks like this is error in your local eslint configuration

Check if json in file `/usr/local/.eslintrc` is valid
