### ISSUE TITLE
glup error in win10 x64

### ISSUE THREAD

**Issue by wangwenta** [akveo/blur-admin#131]
D:\Apache2.2\htdocs\blur-admin-master>gulp serve
[08:55:16] Using gulpfile D:\Apache2.2\htdocs\blur-admin-master\gulpfile.js
[08:55:17] Starting 'scripts'...
[08:55:17] Starting 'styles'...
[08:55:17] 'styles' errored after 106 ms
[08:55:17] Error: %1 is not a valid Win32 application.
\\?\D:\Apache2.2\htdocs\blur-admin-master\node_modules\gulp-sass\node_modules\node-sass\vendor\win32-x64-46\binding.node
    at Error (native)
    at Object.Module._extensions..node (module.js:434:18)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (D:\Apache2.2\htdocs\blur-admin-master\node_modules\gulp-sass\node_modules\node-sass\lib\index.js:24:15)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)

**Comment by vazh** [comment]
works fine on my machine m8.

what is your node & npm version.
have you tried updating your npm ?
