### ISSUE TITLE
Error: Cannot read config package: eslint-config-defaults/configurations/eslint

### ISSUE THREAD

**Issue by SatoMori** [akveo/blur-admin#180]
When I run "gulp serve", following error occur.
Why?

**Comment by ESadouski** [comment]
@SatoMori If the issue is still present please send us the logs.

**Comment by karli2** [comment]
C:\dev\akveo\node_modules\eslint\lib\config\config-file.js:332
            throw e;
            ^

Error: Cannot read config package: eslint-config-defaults/configurations/eslint
Error: Cannot find module 'eslint-config-defaults/configurations/eslint'
Referenced from: C:\Users\haffner\.eslintrc
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at loadPackage (C:\dev\akveo\node_modules\eslint\lib\config\config-file.js:168:16)
    at loadConfigFile (C:\dev\akveo\node_modules\eslint\lib\config\config-file.js:212:18)
    at load (C:\dev\akveo\node_modules\eslint\lib\config\config-file.js:385:18)
    at C:\dev\akveo\node_modules\eslint\lib\config\config-file.js:326:36
    at Array.reduceRight (native)
    at applyExtends (C:\dev\akveo\node_modules\eslint\lib\config\config-file.js:309:28)

**Comment by karli2** [comment]
@SatoMori could you fix this issue? I downloaded the project today and I cannot start the project with gulp

**Comment by karli2** [comment]
ok, fixed it myself. The problem is with the node packages - they need other packages too which are not specified in the package.json:

npm install --save eslint-config-defaults
npm install --save eslint-plugin-react

After running these commands, gulp serve will start the local dev server and open the theme in the browser. However, there are still error messages, for the missing "babl-eslint" package. However, after installing this package the gulp serve command will exit with an error again.

**Comment by kushanlahiruperera** [comment]
@karli2 This introduced another issue. ` error  Cannot find module 'babel-eslint'`
![image](https://cloud.githubusercontent.com/assets/10278585/21968485/0804d116-dbbb-11e6-8ab2-7b4c62b9e410.png)

**Comment by abhishekborole** [comment]
same problem for me as well. Is there any solution you found?

**Comment by abhishekborole** [comment]
After deletion of C:\Users\{username}\.eslintrc
We dont need to install eslint as its not required by blur-admin

**Comment by almgwary** [comment]
same problem for me as well. Is there any solution you found?

**Comment by almgwary** [comment]
Solved: delete this file  `C:\Users\{username}\.eslintrc`

**Comment by nelsonc24** [comment]
Great @almgwary

**Comment by paulkelly2000** [comment]
I had this error.  I had just installed Visual Studio Code before the error started showing up.  I wonder if the error is related to that installation.

**Comment by XBITSwitzerland** [comment]
@almgwary
