### ISSUE TITLE
what happens??

### ISSUE THREAD

**Issue by jipengfei123** [akveo/blur-admin#199]
D:\WorkSpace\WebStorm\blur-admin\node_modules\eslint\lib\config\config-file.js:332
            throw e;
            ^

Error: Cannot read config package: eslint-config-defaults/configurations/eslint
Error: Cannot find module 'eslint-config-defaults/configurations/eslint'
Referenced from: C:\Users\martin\.eslintrc
    at Function.Module._resolveFilename (module.js:472:15)
    at Function.Module._load (module.js:420:25)
    at Module.require (module.js:500:17)
    at require (internal/module.js:20:19)
    at loadPackage (D:\WorkSpace\WebStorm\blur-admin\node_modules\eslint\lib\config\config-file.js:168:16)
    at loadConfigFile (D:\WorkSpace\WebStorm\blur-admin\node_modules\eslint\lib\config\config-file.js:212:18)
    at load (D:\WorkSpace\WebStorm\blur-admin\node_modules\eslint\lib\config\config-file.js:385:18)
    at D:\WorkSpace\WebStorm\blur-admin\node_modules\eslint\lib\config\config-file.js:326:36
    at Array.reduceRight (native)
    at applyExtends (D:\WorkSpace\WebStorm\blur-admin\node_modules\eslint\lib\config\config-file.js:309:28)

**Comment by vlaad360** [comment]
Maybe, you need to try install eslint as global package

**Comment by lugovsky** [comment]
@jipengfei123 hey I would suggest you to look at this issue
https://github.com/AtomLinter/linter-eslint/issues/213
