### ISSUE TITLE
run gulp error

### ISSUE THREAD

**Issue by gadzan** [akveo/blur-admin#21]
At "Run gulp to build sources", 

[12:54:44] Using gulpfile ~/blur-admin/gulpfile.js
[12:54:44] Starting 'clean'...
[12:54:44] Finished 'clean' after 30 ms
[12:54:44] Starting 'default'...
[12:54:44] Starting 'scripts'...
[12:54:44] Starting 'styles'...
[12:54:45] 'styles' errored after 51 ms
[12:54:45]Error: ENOENT: no such file or directory, scandir '/blur-admin/node_modules/.npminstall/node-sass/3.5.1/node-sass/vendor'
    at Error (native)
    at Object.fs.readdirSync (fs.js:808:18)
    at Object.getInstalledBinaries (/blur-admin/node_modules/.npminstall/node-sass/3.5.1/node-sass/lib/extensions.js:60:13)
    at foundBinariesList (/blur-admin/node_modules/.npminstall/node-sass/3.5.1/node-sass/lib/errors.js:19:15)
    at foundBinaries (/blur-admin/node_modules/.npminstall/node-sass/3.5.1/node-sass/lib/errors.js:14:5)
    at Object.module.exports.missingBinary (/blur-admin/node_modules/.npminstall/node-sass/3.5.1/node-sass/lib/errors.js:44:5)
    at Object.<anonymous> (/blur-admin/node_modules/.npminstall/node-sass/3.5.1/node-sass/lib/index.js:14:28)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
[12:54:45] Finished 'default' after 262 ms
[12:54:45] gulp-inject 56 files into main.scss.
[12:54:46] all files 229.97 kB
[12:54:46] Finished 'scripts' after 1.75 s

**Comment by xinconan** [comment]
I also have the gulp error：
[08:48:31] Using gulpfile ~/Desktop/blur-admin-1.1.1/gulpfile.js
[08:48:31] Starting 'clean'...
[08:48:31] Finished 'clean' after 125 ms
[08:48:31] Starting 'default'...
[08:48:31] Starting 'scripts'...
[08:48:33] Starting 'styles'...
[08:48:34] Starting 'stylesAuth'...
[08:48:34] Starting 'styles404'...
[08:48:34] Starting 'copyVendorImages'...
[08:48:34] Starting 'partials'...
[08:48:35] Starting 'fonts'...
[08:48:36] Finished 'default' after 4.26 s
[08:48:41] Finished 'styles404' after 6.08 s
[08:48:41] Starting 'inject404'...
[08:48:41] Finished 'stylesAuth' after 6.12 s
[08:48:41] Starting 'injectAuth'...
[08:48:41] gulp-inject 1 files into 404.html.
[08:48:41] gulp-inject 1 files into auth.html.
[08:48:41] Finished 'inject404' after 250 ms
[08:48:41] gulp-inject 1 files into reg.html.
[08:48:41] Finished 'injectAuth' after 308 ms
[08:48:41] gulp-inject 56 files into main.scss.
[08:48:41] [Sass] Error in plugin 'gulp-sass'
Message:
    src/sass/theme/dashboard/_timeline.scss
  196:3  Mixins may not be defined within control directives or other mixins.
Details:
    formatted: Error: Mixins may not be defined within control directives or other mixins.
        on line 196 of src/sass/theme/dashboard/_timeline.scss
>>   @mixin cd-timeline-left-color($color) {
   --^

    column: 3
    line: 196
    file: /Users/xinconan/Desktop/blur-admin-1.1.1/src/sass/theme/dashboard/_timeline.scss
    status: 1
    messageFormatted: src/sass/theme/dashboard/_timeline.scss
  196:3  Mixins may not be defined within control directives or other mixins.
[08:48:41] Finished 'styles' after 8.55 s
[08:48:42] Finished 'fonts' after 6.5 s
[08:48:42] Finished 'copyVendorImages' after 7.45 s
[08:48:42] Starting 'other'...
[08:48:43] Finished 'partials' after 8.39 s
[08:48:43] all files 227.83 kB
[08:48:43] Finished 'scripts' after 12 s
[08:48:43] Starting 'inject'...
[08:48:43] gulp-inject Nothing to inject into index.html.
[08:48:43] gulp-inject 131 files into index.html.
[08:48:43] Finished 'inject' after 222 ms
[08:48:43] Starting 'html'...
[08:48:46] gulp-inject 1 files into 404.html.
[08:48:46] gulp-inject 1 files into auth.html.
[08:48:46] gulp-inject 1 files into index.html.
[08:48:47] gulp-inject 1 files into reg.html.
[08:48:47] release/ maps/styles/404-e83587cd58.css.map 720 B
[08:48:47] release/ maps/styles/auth-677f0be200.css.map 11.92 kB
[08:48:47] release/ maps/styles/auth-677f0be200.css.map 11.92 kB
[08:48:50] release/ maps/styles/vendor-21c0992fa2.css.map 133.59 kB
[08:48:52] release/ maps/styles/vendor-21c0992fa2.css.map 133.59 kB
[08:48:52] release/ maps/styles/vendor-21c0992fa2.css.map 133.59 kB
[08:49:39] release/ maps/scripts/vendor-b902f62ca2.js.map 8.6 MB
[08:49:39] release/ maps/scripts/app-befbc39c93.js.map 533.99 kB
[08:49:39] release/ styles/404-e83587cd58.css 1.01 kB
[08:49:39] release/ styles/auth-677f0be200.css 38.11 kB
[08:49:39] release/ styles/auth-677f0be200.css 38.11 kB
[08:49:39] release/ styles/vendor-21c0992fa2.css 340.66 kB
[08:49:39] release/ styles/vendor-21c0992fa2.css 340.66 kB
[08:49:39] release/ styles/vendor-21c0992fa2.css 340.66 kB
[08:49:39] release/ scripts/vendor-b902f62ca2.js 2.28 MB
[08:49:39] release/ scripts/app-befbc39c93.js 283.07 kB
[08:49:39] release/ 404.html 918 B
[08:49:39] release/ auth.html 2.04 kB
[08:49:39] release/ index.html 1.86 kB
[08:49:39] release/ reg.html 2.21 kB
[08:49:39] release/ all files 13.24 MB
[08:49:39] Finished 'html' after 56 s
[08:49:39] Finished 'other' after 57 s
[08:49:39] Starting 'build'...
[08:49:39] Finished 'build' after 12 μs

**Comment by partizanos** [comment]
Same error 
I am using windows7.
The procedure to set up the project was:

- -npm install


I had to choose angular 1.4 version

- -Gulp


```
[17:19:28] [Sass] Error in plugin 'gulp-sass'
Message:
    src\sass\theme\dashboard\_timeline.scss
  196:3  Mixins may not be defined within control directives or other mixins.
Details:
    formatted: Error: Mixins may not be defined within control directives or other mixins.
        on line 196 of src/sass/theme/dashboard/_timeline.scss
>>   @mixin cd-timeline-left-color($color) {
   --^
```

    column: 3
    line: 196
    file: C:/blablabla/blur-admin-master/src/sass/theme/dashboard/_timeline.scss
    status: 1
    messageFormatted: src\sass\theme\dashboard\_timeline.scss
  196:3  Mixins may not be defined within control directives or other mixins.



- -gulp server


It runs but same error as above is mentioned in console.
The project runs locally but no colors are applied and not correct structure neither.
The chrome console has the following errors:
```
Uncaught TypeError: this.zoomControl.update is not a function
maps.google.com/maps-api-v3/api/js/24/8/util.js:220 Google Maps API warning: NoApiKeys https://developers.google.com/maps/documentation/javascript/error-messages#no-api-keys
```

```
Uncaught TypeError: this.zoomControl.update is not a function
3264ammap.js:144 Uncaught TypeError: this.zoomControl.update is not a functiond.AmMap.d.Class.update @ ammap.js:144d.update @ ammap.js:11(anonymous function) @ ammap.js:3

```
```
Uncaught TypeError: this.zoomControl.update is not a functiond.AmMap.d.Class.update @ ammap.js:144d.update @ ammap.js:11(anonymous function) @ ammap.js:3
```
Screenshot of localhost is attached 
![image](https://cloud.githubusercontent.com/assets/5407188/14746458/06b19b34-08b0-11e6-9588-106162913956.png)

**Comment by nnixaa** [comment]
@xinconan, @partizanos Same here, probably it's some kind of scss version issue? 

As a quick workaround I just moved the **cd-timeline-left-color** mixin which is in the `src/sass/theme/dashboard/_timeline.scss` file on the line 196 out of the parent media condition `@media only screen and (min-width: $resXL) {`, so put it right before the line 156 and ran `gulp serve` again.
Worked for me.

**Comment by lugovsky** [comment]
Strange thing is that this error happens only on OS X :) 
@nnixaa your solution is good, I will push fix to master right away

**Comment by nhoizey** [comment]
Might be related to https://github.com/sass/node-sass/issues/1387#issuecomment-185451183

**Comment by FellipeP** [comment]
is missing the main.css file in the folder src/app
you guys can find the link:

http://akveo.com/blur-admin-mint/styles/app-bcb3293d10.css
