### ISSUE TITLE
npm install throws some errors,bower  ECONFLICT Unable to find suitable version for angular

### ISSUE THREAD

**Issue by guayeguaye** [akveo/blur-admin#232]
npm install command throws many errors.Any ideas?
node version v7.4.0
npm version  4.0.5

`npm install`

Below is error info:

......
bower amcharts-stock#*                               extract archive.tar.gz
bower amcharts-stock#*                              resolved https://github.com/denisvolokh/bower-amcharts-stock.git#22a2d20323
bower                                              ECONFLICT Unable to find suitable version for angular
Error: post install error, please remove node_modules before retry!
Run "C:\Windows\system32\cmd.exe /d /s /c bower install" error, exit code 1
    at ChildProcess.proc.on.code (C:\Users\hp002\AppData\Roaming\npm\node_modules\cnpm\node_modules\runscript\index.js:67:21)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:885:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)

`bower install`

....................
bower raphael#>= 2.0                                validate 2.2.7 against https://github.com/DmitryBaranovskiy/raphael.git#>= 2.0
bower eve-raphael#0.5.0                               cached https://github.com/tomasAlabes/eve.git#0.5.0
bower eve-raphael#0.5.0                             validate 0.5.0 against https://github.com/tomasAlabes/eve.git#0.5.0
bower                                              ECONFLICT Unable to find suitable version for angular

these are my dependencies in the file `bower.json`
"dependencies": {
    "Chart.js": "~1.0.2",
    "Ionicons": "ionicons#~2.0.1",
    "amcharts": "~3.15.2",
    "amcharts-stock": "*",
    "ammap": "~3.14.5",
    "angular": "~1.4.8",
    "angular-route": "~1.4.6",
    "angular-slimscroll": "~1.1.5",
    "angular-smart-table": "~2.1.3",
    "angular-toastr": "~1.7.0",
    "angular-touch": "~1.4.6",
    "angular-ui-sortable": "~0.13.4",
    "animate.css": "~3.4.0",

**Comment by guayeguaye** [comment]
`bower install angular --force-latest`
