### ISSUE TITLE
Error: Error: Chart.js is not installed.

### ISSUE THREAD

**Issue by resultakak** [akveo/blur-admin#28]
Sorry. I can a little speak english. My problem ...

[05:10:08] Using gulpfile /usr/share/nginx/html/blur-admin/gulpfile.js
[05:10:08] Starting 'scripts'...
[05:10:09] Starting 'styles'...
[05:10:09] Starting 'stylesAuth'...
[05:10:09] Starting 'styles404'...
[05:10:09] Starting 'copyVendorImages'...
[05:10:09] Finished 'copyVendorImages' after 27 ms
[05:10:09] Finished 'styles404' after 486 ms
[05:10:09] Starting 'inject404'...
[05:10:09] Finished 'stylesAuth' after 497 ms
[05:10:09] Starting 'injectAuth'...
[05:10:09] gulp-inject 1 files into 404.html.
stream.js:74
      throw er; // Unhandled stream error in pipe.
      ^

Error: Error: Chart.js is not installed. Try running `bower install`.
    at /usr/share/nginx/html/blur-admin/node_modules/wiredep/wiredep.js:30:56
    at /usr/share/nginx/html/blur-admin/node_modules/wiredep/lib/detect-dependencies.js:145:29
    at forOwn (/usr/share/nginx/html/blur-admin/node_modules/wiredep/node_modules/lodash/dist/lodash.js:2106:15)
    at Function.forEach (/usr/share/nginx/html/blur-admin/node_modules/wiredep/node_modules/lodash/dist/lodash.js:3303:9)
    at detectDependencies (/usr/share/nginx/html/blur-admin/node_modules/wiredep/lib/detect-dependencies.js:34:7)
    at wiredep (/usr/share/nginx/html/blur-admin/node_modules/wiredep/wiredep.js:70:39)
    at DestroyableTransform._transform (/usr/share/nginx/html/blur-admin/node_modules/wiredep/wiredep.js:135:34)
    at DestroyableTransform.Transform._read (/usr/share/nginx/html/blur-admin/node_modules/wiredep/node_modules/readable-stream/lib/_stream_transform.js:184:10)
    at DestroyableTransform.Transform._write (/usr/share/nginx/html/blur-admin/node_modules/wiredep/node_modules/readable-stream/lib/_stream_transform.js:172:12)
    at doWrite (/usr/share/nginx/html/blur-admin/node_modules/wiredep/node_modules/readable-stream/lib/_stream_writable.js:237:10)

**Comment by lugovsky** [comment]
Chart js si not installed. Try running
```bash
bower install
```

**Comment by ashwani23** [comment]
I see that the `bower install` command is already ran through `npm install` itself.
I am seeing a same problem but running `bower install` explicitly is not helping. Please get me out of this.

**Comment by sourav26721062** [comment]
@ashwani23 did u got a resolution. I am facing the same issue

**Comment by KrustyC** [comment]
I got same Issue with Chart.js. Chrome loads all the library but when try to load Chart.js appears this error:
Chart.js:1 Unexpected token <. I think it can't find the module Chart.js, but I'm sure that I write the right path.
