### ISSUE TITLE
Not able to gulp serve from scratch

### ISSUE THREAD

**Issue by bobbyziom** [akveo/blur-admin#284]
Installed bower and npm, running gulp serve:

```
$ gulp
module.js:328
    throw err;
    ^

Error: Cannot find module 'vinyl'
    at Function.Module._resolveFilename (module.js:326:15)
    at Function.Module._load (module.js:277:25)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/gulp/node_modules/gulp-util/index.js:2:9)
    at Module._compile (module.js:398:26)
    at Object.Module._extensions..js (module.js:405:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
```

**Comment by bobbyziom** [comment]
`npm install -g gulp`

fixed it

**Comment by felansu** [comment]
@bobbyziom can you close this issue please ?
