### ISSUE TITLE
Error after running gulp serve

### ISSUE THREAD

**Issue by KawtharE** [akveo/blur-admin#293]
After runnig **gulp serve** i got this error:

[20:40:11] 'watch' errored after 11 ms
[20:40:11] Error: watch /var/www/html/blur-admin/ ENOSPC
    at exports._errnoException (util.js:1018:11)
    at FSWatcher.start (fs.js:1443:19)
    at Object.fs.watch (fs.js:1470:11)
    at Gaze._watchDir (/var/www/html/blur-admin/node_modules/gaze/lib/gaze.js:289:30)
    at /var/www/html/blur-admin/node_modules/gaze/lib/gaze.js:358:10
    at iterate (/var/www/html/blur-admin/node_modules/gaze/lib/helper.js:52:5)
    at /var/www/html/blur-admin/node_modules/gaze/lib/helper.js:61:11
    at /var/www/html/blur-admin/node_modules/gaze/lib/gaze.js:420:5
    at iterate (/var/www/html/blur-admin/node_modules/gaze/lib/helper.js:52:5)
    at Object.forEachSeries (/var/www/html/blur-admin/node_modules/gaze/lib/helper.js:66:3)

In fact, it works for me fine for the first time and now only **gulp serve:dist** works fine.
Any idea about this error?

**Comment by peregrino78** [comment]
After install bower and run "bower install" The admin panel it's ok run...i
havia study more...thanks for your attention.

Em 23 de mai de 2017 4:43 PM, "Kawthar" <notifications@github.com> escreveu:

**Comment by KawtharE** [comment]
@peregrino78  it is working now! i guess the problem was in my localhost, there is no issue in the template :)  great job guys :+1:
