### ISSUE TITLE
Adopting Blur-admin with python backend

### ISSUE THREAD

**Issue by Amrizhan** [akveo/blur-admin#329]
Hi AKVEO!!!
I am trying to integrate Blur-Admin with Django Python. I have created standard release with default data and faced with next error

> TypeError: this.zoomControl.update is not a function[Learn More] vendor-b82c564ee5.js:269:14754
	update http://localhost:8000/static/scripts/vendor-b82c564ee5.js:269:14754
	t.update http://localhost:8000/static/scripts/vendor-b82c564ee5.js:267:8721
	t.addChart/t.updateInt< http://localhost:8000/static/scripts/vendor-b82c564ee5.js:267:4553
	enter resource://devtools/server/actors/script.js:350:5
	bound enter self-hosted:911:17
	_pushThreadPause resource://devtools/server/actors/script.js:533:5
	_pauseAndRespond resource://devtools/server/actors/script.js:741:7
	pauseAndRespond resource://devtools/server/actors/script.js:870:16
	_makeOnStep/< resource://devtools/server/actors/script.js:803:16
	s_.MB https://www.google.com/xjs/_/js/k=xjs.s.en.l1hK0cKlHms.O/m=sx,c,sb,cdos,cr,elog,hsm,jsa,r,qsm,d,csi/am=gEUYOV5wAOT_hFAYuIWwQFLAxAEE/rt=j/d=1/t=zcms/rs=ACT90oEifj6bjWpMU13_3YoYmVIF-PlqQw:115:1
	s_.dispatchEvent https://www.google.com/xjs/_/js/k=xjs.s.en.l1hK0cKlHms.O/m=sx,c,sb,cdos,cr,elog,hsm,jsa,r,qsm,d,csi/am=gEUYOV5wAOT_hFAYuIWwQFLAxAEE/rt=j/d=1/t=zcms/rs=ACT90oEifj6bjWpMU13_3YoYmVIF-PlqQw:113:345
	s_.bI https://www.google.com/xjs/_/js/k=xjs.s.en.l1hK0cKlHms.O/m=sx,c,sb,cdos,cr,elog,hsm,jsa,r,qsm,d,csi/am=gEUYOV5wAOT_hFAYuIWwQFLAxAEE/rt=j/d=1/t=zcms/rs=ACT90oEifj6bjWpMU13_3YoYmVIF-PlqQw:561:275
	s_.ZV https://www.google.com/xjs/_/js/k=xjs.s.en.l1hK0cKlHms.O/m=sx,c,sb,cdos,cr,elog,hsm,jsa,r,qsm,d,csi/am=gEUYOV5wAOT_hFAYuIWwQFLAxAEE/rt=j/d=1/t=zcms/rs=ACT90oEifj6bjWpMU13_3YoYmVIF-PlqQw:561:172
	bound  self-hosted:911:17

        Can you please give a tips to fix that?

**Comment by cmchecha** [comment]
For what is that?. I already integrated Django with this template

**Comment by ThangBK2009** [comment]
@cmchecha can u share me a example project u intergrated with Django or Flask

**Comment by cmchecha** [comment]
@ThangBK2009 Actually I am deploying the app. As soon as I finish, I'll upload an example to github.

**Comment by ThangBK2009** [comment]
@cmchecha thank u so much

**Comment by cmchecha** [comment]
I'm working on this project. This week will be finished the first version of the example @ThangBK2009

**Comment by cmchecha** [comment]
@delhipnr I made a full project with Django as backend and Akveo Blur Admin Template as frontend but this project is posted on Bitbucket. The frontend of this project was based on this template with AngularJS, and backend is Django 1.11 with Django REST Framework. Check this https://bitbucket.org/account/user/mskstems/projects/FTK

**Comment by alexwhen** [comment]
@cesarfmacario  gulp serve

assert.js:348
    throw err;
    ^

AssertionError [ERR_ASSERTION]: Task function must be specified
    at Gulp.set [as _setTask] (/Users/alex/talita-kum-web-frontend/node_modules/undertaker/lib/set-task.js:10:3)
    at Gulp.task (/Users/alex/talita-kum-web-frontend/node_modules/undertaker/lib/task.js:13:8)
    at Object.<anonymous> (/Users/alex/talita-kum-web-frontend/gulp/build.js:28:6)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:20:18)
