### ISSUE TITLE
IMPOSIBLE INSTALL

### ISSUE THREAD

**Issue by jcnavamorffe** [akveo/blur-admin#332]
HELLO GUYS...

i try to install the theme ... and show me this after npm install

make: *** [Release/obj.target/libsass/src/libsass/src/ast.o] Error 1
make: Leaving directory `/home/cabox/workspace/blur-admin/node_modules/node-sass/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/cabox/workspace/blur-admin/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:125:13)
gyp ERR! stack     at ChildProcess.emit (events.js:213:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Linux 2.6.32-042stab112.15
gyp ERR! command "/usr/local/bin/node" "/home/cabox/workspace/blur-admin/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd /home/cabox/workspace/blur-admin/node_modules/node-sass
gyp ERR! node -v v8.4.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
Build failed with error code: 1
npm WARN blur_admin@1.3.1 No repository field.
npm WARN blur_admin@1.3.1 No license field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.2 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

**Comment by kinibai** [comment]
I have install it on Win7 successfully by offline install related package, maybe you can try this also

**Comment by allanfann** [comment]
same as #335

**Comment by purplelabmice** [comment]
Hi,

i think you need go to package.json..then change version no for for this item "gulp-sass": "~3.0.0", ... then try to run npm install again...if still facing an error then try remove folder node_modules then again need to run npm install...
