### ISSUE TITLE
Centos gulp serve:dist not working

### ISSUE THREAD

**Issue by vikash159** [akveo/blur-admin#333]
[14:47:39] Using gulpfile ~/attack-front/gulpfile.js
[14:47:39] Starting 'scripts'...
[14:47:40] Starting 'styles'...
[14:47:40] 'styles' errored after 68 ms
[14:47:40] Error: Cannot find any-promise implementation nor global.Promise. You must install polyfill or call require("any-promise/register") with your preferred implementation, e.g. require("any-promise/register/bluebird") on application load prior to any require("any-promise").
    at loadImplementation (/home/centos/attack-front/node_modules/gulp-inject/node_modules/stream-to-array/node_modules/any-promise/register.js:37:11)
    at register (/home/centos/attack-front/node_modules/gulp-inject/node_modules/stream-to-array/node_modules/any-promise/loader.js:67:22)
    at Object.<anonymous> (/home/centos/attack-front/node_modules/gulp-inject/node_modules/stream-to-array/node_modules/any-promise/index.js:1:101)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/home/centos/attack-front/node_modules/gulp-inject/node_modules/stream-to-array/index.js:2:15)
all files 996.19 kB
Finished 'scripts' after 4.13 s

**Comment by kamane** [comment]
+1 having the same issue 

gulp serve 




[16:09:57] Using gulpfile /home/loc/www/wp-content/loc/1/blur-admin/gulpfile.js
[16:09:57] Starting 'scripts'...
[16:09:57] Starting 'styles'...
[16:09:57] 'styles' errored after 99 ms
[16:09:57] Error: Cannot find any-promise implementation nor global.Promise. You must install polyfill or call require("any-promise/register") with your preferred implementation, e.g. require("any-promise/register/bluebird") on application load prior to any require("any-promise").
    at loadImplementation (/home/loc/www/wp-content/loc/1/blur-admin/node_modules/gulp-inject/node_modules/stream-to-array/node_modules/any-promise/register.js:37:11)
    at register (/home/loc/www/wp-content/loc/1/blur-admin/node_modules/gulp-inject/node_modules/stream-to-array/node_modules/any-promise/loader.js:67:22)
    at Object.<anonymous> (/home/loc/www/wp-content/loc/1/blur-admin/node_modules/gulp-inject/node_modules/stream-to-array/node_modules/any-promise/index.js:1:101)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/home/loc/www/wp-content/loc/1/blur-admin/node_modules/gulp-inject/node_modules/stream-to-array/index.js:2:15)
[16:09:59] all files 244.11 kB
[16:09:59] Finished 'scripts' after 1.86 s

**Comment by kamane** [comment]
1 make sure you have this installed with npm install :  bluebird /mz / polyfills 

2 then run gulp serve 
if you face an error that mentionning :Promise is not defined  follow step 3 



3 optionnal : 

install                   " npm install es6-promise --save   " 

and add this " require('es6-promise').polyfill(); " at line 5 of this file gulpfile.js  --> located under /blur-admin/

**Comment by elahmed26** [comment]
Hello !
I have a problem running the command gulp serve: dist for my deployment. I have this error:

```
PS D:\remotefolder\Front App\worflow> gulp serve:dist
[13:41:36] Using gulpfile D:\remotefolder\Front App\worflow\gulpfile.js
[13:41:36] Starting 'scripts'...
[13:41:39] Starting 'styles'...
[13:41:45] Starting 'stylesAuth'...
[13:41:45] Starting 'styles404'...
[13:41:45] Starting 'copyVendorImages'...
[13:41:45] Starting 'partials'...
[13:41:47] Starting 'fonts'...
[13:41:52] Finished 'stylesAuth' after 7.17 s
[13:41:52] Starting 'injectAuth'...
[13:41:52] Finished 'styles404' after 7.18 s
[13:41:52] Starting 'inject404'...
[13:41:52] gulp-inject 1 files into 404.html.
[13:41:53] gulp-inject 1 files into auth.html.
[13:41:53] gulp-inject 1 files into reg.html.
[13:41:53] Finished 'inject404' after 702 ms
[13:41:53] Finished 'injectAuth' after 742 ms
[13:41:53] gulp-inject 52 files into main.scss.
[13:41:53] Finished 'fonts' after 6.2 s
[13:41:54] Finished 'styles' after 15 s
[13:41:54] Finished 'copyVendorImages' after 9.1 s
[13:41:54] Starting 'other'...
[13:41:55] Finished 'partials' after 9.75 s
[13:41:56] all files 187.7 kB
[13:41:56] Finished 'scripts' after 20 s
[13:41:56] Starting 'inject'...
[13:41:56] gulp-inject 1 files into index.html.
[13:41:56] gulp-inject 118 files into index.html.
[13:41:56] Finished 'inject' after 237 ms
[13:41:56] Starting 'html'...
[13:42:06] gulp-inject Nothing to inject into 404.html.
[13:42:06] gulp-inject Nothing to inject into auth.html.
[13:42:06] gulp-inject 1 files into index.html.
[13:42:07] gulp-inject Nothing to inject into reg.html.
[13:42:07] release\ maps\styles\404-447480c9a8.css.map 673 B
[13:42:07] release\ maps\styles\auth-3e3da005b1.css.map 12.75 kB
[13:42:07] release\ maps\styles\app-90729615c8.css.map 52.35 kB
[13:42:07] release\ maps\styles\auth-3e3da005b1.css.map 12.75 kB
[13:42:13] release\ maps\styles\vendor-aa081b2d58.css.map 139.28 kB
[13:42:13] release\ maps\styles\vendor-aa081b2d58.css.map 139.28 kB
[13:42:13] release\ maps\styles\vendor-aa081b2d58.css.map 139.28 kB
events.js:161
      throw er; // Unhandled 'error' event
      ^

Error: StringMap expected string key
    at stringmap.set (D:\remotefolder\Front App\worflow\node_modules\stringmap\stringmap.js:99:19)
    at Scope.add (D:\remotefolder\Front App\worflow\node_modules\ng-annotate\build\es5\scope.js:102:17)
    at D:\remotefolder\Front App\worflow\node_modules\ng-annotate\build\es5\scopetools.js:38:25
    at Array.forEach (native)
    at createScopes (D:\remotefolder\Front App\worflow\node_modules\ng-annotate\build\es5\scopetools.js:36:27)
    at visit (D:\remotefolder\Front App\worflow\node_modules\ordered-ast-traverse\ordered-ast-traverse.js:25:19)
    at visit (D:\remotefolder\Front App\worflow\node_modules\ordered-ast-traverse\ordered-ast-traverse.js:43:25)
    at visit (D:\remotefolder\Front App\worflow\node_modules\ordered-ast-traverse\ordered-ast-traverse.js:46:21)
    at visit (D:\remotefolder\Front App\worflow\node_modules\ordered-ast-traverse\ordered-ast-traverse.js:43:25)
    at traverse (D:\remotefolder\Front App\worflow\node_modules\ordered-ast-traverse\ordered-ast-traverse.js:56:5)
PS D:\remotefolder\Front App\worflow>
```

Here is my work environment:
Windows **10**
gulp CLI version **1.4.0**; Local version **3.9.1**
nodejs : **v7.5.0**
npm: **4.1.2**

please, is there anyone to help me ?

**Comment by iamcoming94** [comment]
@elahmed26 I am having this issue too. Did you found solution?
