### ISSUE TITLE
bower install fails on windows 10

### ISSUE THREAD

**Issue by joshapearson** [akveo/blur-admin#342]
97 verbose stack Error: blur_admin@1.3.1 postinstall: `bower install`
97 verbose stack Exit status 1
97 verbose stack     at EventEmitter.<anonymous> (C:\Program Files (x86)\nodejs\node_modules\npm\lib\utils\lifecycle.js:255:16)
97 verbose stack     at emitTwo (events.js:106:13)
97 verbose stack     at EventEmitter.emit (events.js:191:7)
97 verbose stack     at ChildProcess.<anonymous> (C:\Program Files (x86)\nodejs\node_modules\npm\lib\utils\spawn.js:40:14)
97 verbose stack     at emitTwo (events.js:106:13)
97 verbose stack     at ChildProcess.emit (events.js:191:7)
97 verbose stack     at maybeClose (internal/child_process.js:920:16)
97 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:230:5)
98 verbose pkgid blur_admin@1.3.1
99 verbose cwd C:\Users\jpearson\blur-admin
100 error Windows_NT 10.0.15063
101 error argv "C:\\Program Files (x86)\\nodejs\\node.exe" "C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
102 error node v6.11.3
103 error npm  v3.10.10
104 error code ELIFECYCLE
105 error blur_admin@1.3.1 postinstall: `bower install`
105 error Exit status 1
106 error Failed at the blur_admin@1.3.1 postinstall script 'bower install'.
106 error Make sure you have the latest version of node.js and npm installed.
106 error If you do, this is most likely a problem with the blur_admin package,
106 error not with npm itself.
106 error Tell the author that this fails on your system:
106 error     bower install
106 error You can get information on how to open an issue for this project with:
106 error     npm bugs blur_admin
106 error Or if that isn't available, you can get their info via:
106 error     npm owner ls blur_admin
106 error There is likely additional logging output above.
107 verbose exit [ 1, true ]

In attempting to use NPM install on windows 10, vs Code. I keep receiving this issue. Specifically where the bower install fails consistently. I have installed bower using NPM install -g bower, but with no luck actually getting it to work. Any help is appreciated

**Comment by shmulim** [comment]
Install Bower using `npm install -g bower` and then run `npm install` again. This resolved the issue for me.
