### ISSUE TITLE
if i clone this project ,how to run it?

### ISSUE THREAD

**Issue by flyingrookie** [akveo/blur-admin#370]
Pls tell me the metod of running this project! 3Q!!!

**Comment by cmchecha** [comment]
You need to install node, npm, bower and gulp in your system.
`sudo npm install bower -g`
`sudo npm install gulp -g`


To run:
`gulp serve`

**Comment by RoraxHan** [comment]
`npm install`
this will install node packages and bower packages.
and 
`gulp serve`

**Comment by shubham-matale** [comment]
After running command
`gulp serve` i got following error

`fs.js:27
const { Math, Object } = primordials;
                         ^

ReferenceError: primordials is not defined
    at fs.js:27:26
    at req_ (/home/shubhammatale/Documents/Test/blur-admin/node_modules/natives/index.js:143:24)
    at Object.req [as require] (/home/shubhammatale/Documents/Test/blur-admin/node_modules/natives/index.js:55:10)
    at Object.<anonymous> (/home/shubhammatale/Documents/Test/blur-admin/node_modules/vinyl-fs/node_modules/graceful-fs/fs.js:1:37)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:643:32)
    at Function.Module._load (internal/modules/cjs/loader.js:556:12)
    at Module.require (internal/modules/cjs/loader.js:683:19)
    at require (internal/modules/cjs/helpers.js:16:16)
`

**Comment by raghulrajnkl** [comment]
First of All Find Your package.json and in the same directory create an npm-shrinkwrap.json file with the following contents

{
  "dependencies": {
    "graceful-fs": {
        "version": "4.2.2"
     }
  }
}

2. Now, Just Run npm install. it will update npm-shrinkwrap.json with a bunch of content.

It will solve Your Error

**Comment by karlaguerreiro** [comment]
I have the same problem and the solutions above did not help at all
