### ISSUE TITLE
error: node sass does not yet support    win 64  node v8.93

### ISSUE THREAD

**Issue by readying** [akveo/blur-admin#376]
When I runing the 'gulp serve', it not run normally, how can I solve it? Any ideas, thanks advance.

[19:29:01] Using gulpfile E:\git\blur-admin\gulpfile.js
[19:29:01] Starting 'scripts'...
[19:29:03] Starting 'styles'...
[19:29:04] 'styles' errored after 678 ms
[19:29:04] Error: Node Sass does not yet support your current environment: Windows 64-bit with Unsupported runtime (57)
For more information on which environments are supported please see:
https://github.com/sass/node-sass/releases/tag/v3.13.1
    at module.exports (E:\git\blur-admin\node_modules\_node-sass@3.13.1@node-sass\lib\binding.js:13:13)
    at Object.<anonymous> (E:\git\blur-admin\node_modules\_node-sass@3.13.1@node-sass\lib\index.js:14:35)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (E:\git\blur-admin\node_modules\_gulp-sass@2.3.2@gulp-sass\index.js:187:21)
[19:29:05] gulp-inject 52 files into main.scss.
[19:29:06] all files 252.78 kB
[19:29:06] Finished 'scripts' after 4.35 s

**Comment by Dgiulian** [comment]
Remove and reinstall the node-sass package, or just update the version in the package.json to 3.1.1 before doing `npm install`
`npm remove node-sass
 npm install node-sass --save-dev`

**Comment by Nitinrajyadav** [comment]
you can try  **npm rebuild node-sass**

for more details, have a look [https://github.com/sass/node-sass/issues/1764](https://github.com/sass/node-sass/issues/1764)

**Comment by przemyslvw** [comment]
npm --depth 9999 update
npm rebuild node-sass
