### ISSUE TITLE
npm install failed

### ISSUE THREAD

**Issue by cnuis2cool** [akveo/blur-admin#385]
31355 warn blur_admin@1.3.1 No repository field.
31356 warn blur_admin@1.3.1 No license field.
31357 warn optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.3 (node_modules\fsevents):
31358 warn notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
31359 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Valid OS:    darwin
31359 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Valid Arch:  any
31359 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Actual OS:   win32
31359 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Actual Arch: x64
31360 verbose stack Error: node-sass@3.13.1 postinstall: `node scripts/build.js`
31360 verbose stack Exit status 1
31360 verbose stack     at EventEmitter.<anonymous> (C:\Users\spanugan\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\index.js:285:16)
31360 verbose stack     at emitTwo (events.js:125:13)
31360 verbose stack     at EventEmitter.emit (events.js:213:7)
31360 verbose stack     at ChildProcess.<anonymous> (C:\Users\spanugan\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
31360 verbose stack     at emitTwo (events.js:125:13)
31360 verbose stack     at ChildProcess.emit (events.js:213:7)
31360 verbose stack     at maybeClose (internal/child_process.js:927:16)
31360 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
31361 verbose pkgid node-sass@3.13.1
31362 verbose cwd F:\MyProjs\2. Admin Templates\blur-admin
31363 verbose Windows_NT 10.0.14393
31364 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\spanugan\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install"
31365 verbose node v8.7.0
31366 verbose npm  v5.6.0
31367 error code ELIFECYCLE
31368 error errno 1
31369 error node-sass@3.13.1 postinstall: `node scripts/build.js`
31369 error Exit status 1
31370 error Failed at the node-sass@3.13.1 postinstall script.
31370 error This is probably not a problem with npm. There is likely additional logging output above.
31371 verbose exit [ 1, true ]

**Comment by yvonneliu121** [comment]
Hi cnuis2cool,
Did you resolve this problem? I came across the same problem.

**Comment by cnuis2cool** [comment]
@yvonneliu121 Nope

**Comment by yvonneliu121** [comment]
Fixed it. Download BlurAdmin from http://akveo.github.io/blur-admin/articles/091-downloads/ under your htdocs folder, install Python2.7 instead of Python3 and npm audit(use "npm install -save-dev" to install missing packages). Then run the localhost/your folder name~click "release"(production mode) or "dev-release"(development mode)

**Comment by cnuis2cool** [comment]
Thank you.
