### ISSUE TITLE
Gulp serve issue

### ISSUE THREAD

**Issue by XBITSwitzerland** [akveo/blur-admin#394]
$ gulp serve
[15:11:55] Using gulpfile C:\github\blur-admin\gulpfile.js
[15:11:55] Starting 'scripts'...
[15:11:56] Starting 'styles'...
[15:11:56] Starting 'stylesAuth'...
[15:11:56] Starting 'styles404'...
[15:11:56] Starting 'copyVendorImages'...
C:\github\blur-admin\node_modules\eslint\lib\config\config-file.js:332
            throw e;
            ^

Error: Cannot read config package: eslint-config-defaults/configurations/eslint
Error: Cannot find module 'eslint-config-defaults/configurations/eslint'
Referenced from: C:\Users\danyb\.eslintrc
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at loadPackage (C:\github\blur-admin\node_modules\eslint\lib\config\config-file.js:168:16)
    at loadConfigFile (C:\github\blur-admin\node_modules\eslint\lib\config\config-file.js:212:18)
    at load (C:\github\blur-admin\node_modules\eslint\lib\config\config-file.js:385:18)
    at C:\github\blur-admin\node_modules\eslint\lib\config\config-file.js:326:36
    at Array.reduceRight (<anonymous>)
    at applyExtends (C:\github\blur-admin\node_modules\eslint\lib\config\config-file.js:309:28)

**Comment by XBITSwitzerland** [comment]
The Issue was to delete: C:\Users\{username}\.eslintrc
