### ISSUE TITLE
inject

### ISSUE THREAD

**Issue by ankitg1602** [akveo/blur-admin#42]
Actually I want to inject ngcsv and ngSanitize .I injected in app.js  file. After that in index.html i given the path of both the file.In controller folder I injected the same.but i am getting the error  [$injector:unpr] Unknown provider: ngCsvProvider <- ngCsv <- ShowSurveyResultCtrl
http://errors.angularjs.org/1.5.6/$injector/unpr?p0=ngCsvProvider%20%3C-%20ngCsv%20%3C-%20ShowSurveyResultCtrl
    at http://localhost:3000/bower_components/angular/angular.js:68:12
    at http://localhost:3000/bower_components/angular/angular.js:4501:19
    at Object.getService [as get] (http://localhost:3000/bower_components/angular/angular.js:4654:39)
    at http://localhost:3000/bower_components/angular/angular.js:4506:45
    at getService (http://localhost:3000/bower_components/angular/angular.js:4654:39)
    at injectionArgs (http://localhost:3000/bower_components/angular/angular.js:4678:58)
    at Object.instantiate (http://localhost:3000/bower_components/angular/angular.js:4720:18)
    at $controller (http://localhost:3000/bower_components/angular/angular.js:10192:28)
    at Object.<anonymous> (http://localhost:3000/bower_components/angular-ui-router/release/angular-ui-router.js:4081:28)
    at http://localhost:3000/bower_components/angular/angular.js:1266:18 <ui-view class="ng-scope">

**Comment by ankitg1602** [comment]
I got my mistake.Thanks

**Comment by lugovsky** [comment]
Okay, closing the issue then
