### ISSUE TITLE
Hi!

### ISSUE THREAD

**Issue by FranciscoPereir** [akveo/blur-admin#47]

**Comment by FranciscoPereir** [comment]
Hi, when i try to run gulp build i have always the same error message: 

 `Error: Cannot find module 'gulp-minify-html'     at Function.Module._resolveFilename (module.js:337:15)     at Function.Module._load (module.js:287:25)     at Module.require (module.js:366:17)     at require (module.js:385:17)     at requireFn (C:\MAMP\htdocs\blur-admin\node_modules\gulp-load-plugins\index.js:40:16)     at Object.defineProperty.get (C:\MAMP\htdocs\blur-admin\node_modules\gulp-load-plugins\index.js:65:18)     at Gulp.<anonymous> (C:\MAMP\htdocs\blur-admin\gulp\build.js:16:12)     at module.exports (C:\MAMP\htdocs\blur-admin\node_modules\orchestrator\lib\runTask.js:34:7)     at Gulp.Orchestrator._runTask (C:\MAMP\htdocs\blur-admin\node_modules\orchestrator\index.js:273:3)     at Gulp.Orchestrator._runStep (C:\MAMP\htdocs\blur-admin\node_modules\orchestrator\index.js:214:10).` 

I already installed the module, but the error is still there. 
I also used the generator-gulp-angular in a yeoman project and it´s working. Only on blur-admin do i have this problem.
