### ISSUE TITLE
Cannot install on Ubuntu 18.04?

### ISSUE THREAD

**Issue by Aspire21** [akveo/blur-admin#519]
I ran:
sudo npm install bower -g
sudo npm install gulp -g

then 

npm install
gulp serve

This is the error i get:

```
ReferenceError: primordials is not defined
    at fs.js:36:5
    at req_ (/root/blur-admin/node_modules/natives/index.js:143:24)
    at Object.req [as require] (/root/blur-admin/node_modules/natives/index.js:55:10)
    at Object.<anonymous> (/root/blur-admin/node_modules/vinyl-fs/node_modules/graceful-fs/fs.js:1:37)
    at Module._compile (internal/modules/cjs/loader.js:1137:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
    at Module.load (internal/modules/cjs/loader.js:985:32)
    at Function.Module._load (internal/modules/cjs/loader.js:878:14)
    at Module.require (internal/modules/cjs/loader.js:1025:19)
    at require (internal/modules/cjs/helpers.js:72:18)

```
How can i fix this?

**Comment by SMN947** [comment]
@Aspire21 It seems like gulp and node versions have some conflicts. Try this:
https://stackoverflow.com/questions/55921442/how-to-fix-referenceerror-primordials-is-not-defined-in-node
