### ISSUE TITLE
TypeError: Cannot read property 'on' of undefined

### ISSUE THREAD

**Issue by wanderingies** [akveo/blur-admin#522]
[19:18:49] Starting 'clean'...
[19:18:49] Finished 'clean' after 13 ms
[19:18:49] Starting 'default'...
[19:18:49] Starting 'scripts'...
[19:18:49] Starting 'styles'...
I like threesomes cause I'm the Man In The Middle!
[19:18:50] 'styles' errored after 1.86 ms
[19:18:50] TypeError: Cannot read property 'on' of undefined
    at DestroyableTransform.Readable.pipe (D:\Source\ulpay\blur-admin\node_modules\vinyl-fs\node_modules\readable-stream\lib\_stream_readable.js:516:8)
    at buildStyles (D:\Source\ulpay\blur-admin\gulp\styles.js:64:8)
    at Gulp.<anonymous> (D:\Source\ulpay\blur-admin\gulp\styles.js:20:10)
    at module.exports (D:\Source\ulpay\blur-admin\node_modules\orchestrator\lib\runTask.js:34:7)
    at Gulp.Orchestrator._runTask (D:\Source\ulpay\blur-admin\node_modules\orchestrator\index.js:273:3)
    at Gulp.Orchestrator._runStep (D:\Source\ulpay\blur-admin\node_modules\orchestrator\index.js:214:10)
    at Gulp.Orchestrator.start (D:\Source\ulpay\blur-admin\node_modules\orchestrator\index.js:134:8)
    at Gulp.<anonymous> (D:\Source\ulpay\blur-admin\gulpfile.js:22:8)
    at module.exports (D:\Source\ulpay\blur-admin\node_modules\orchestrator\lib\runTask.js:34:7)
    at Gulp.Orchestrator._runTask (D:\Source\ulpay\blur-admin\node_modules\orchestrator\index.js:273:3)
[19:18:50] Finished 'default' after 123 ms
[19:18:50] all files 252.78 kB
[19:18:50] Finished 'scripts' after 907 ms

**\gulp\styles.js**
```
function debug() {
  var stream = arguments[0];

  // put your desired debugging gode here
  console.log ("I like threesomes cause I'm the Man In The Middle!");

  return stream;
}
```

```
  return gulp.src([
    path.join(conf.paths.src, '/sass/main.scss')
  ])
      .pipe(debug())
      .pipe($.inject(injectFiles, injectOptions))
      .pipe(wiredep(_.extend({}, conf.wiredep)))
      .pipe($.sourcemaps.init())
      .pipe($.sass(sassOptions)).on('error', conf.errorHandler('Sass'))
      .pipe($.autoprefixer()).on('error', conf.errorHandler('Autoprefixer'))
      .pipe($.sourcemaps.write())
      .pipe(gulp.dest(path.join(conf.paths.tmp, '/serve/app/')));
};
```

**release\styles\app-8df6ba4572.css**   
The size of this file is only 2kb, which is obviously abnormal. I tried to add the above code, which prompted this error. I tried it, but it still can't be solved.

**Comment by wanderingies** [comment]
upgrade gulp-inject in package.json to 5.0.3
