### ISSUE TITLE
Cant gulp serve the project

### ISSUE THREAD

**Issue by Black4ce** [akveo/blur-admin#523]
if im using gulp serve i get the following error

`E:\Project\blur-admin>gulp serve
AssertionError [ERR_ASSERTION]: Task function must be specified
    at Gulp.set [as _setTask] (E:\Project\blur-admin\node_modules\undertaker\lib\set-task.js:10:3)
    at Gulp.task (E:\Project\blur-admin\node_modules\undertaker\lib\task.js:13:8)
    at Object.<anonymous> (E:\Project\blur-admin\gulp\build.js:28:6)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at E:\Project\blur-admin\gulpfile.js:13:3 {
  generatedMessage: false,
  code: 'ERR_ASSERTION',
  actual: false,
  expected: true,
  operator: '=='
}`

im using gulp 4.0.0

line 13:3 im gulpfile is:

`  require('./gulp/' + file);`

` wrench.readdirSyncRecursive('./gulp').filter(function(file) {
  return (/\.(js|coffee)$/i).test(file);
}).map(function(file) {
  require('./gulp/' + file);
});`

**Comment by nitinmukesh** [comment]
I am getting the following error

C:\blur-admin-master>gulp server
ReferenceError: primordials is not defined
    at fs.js:45:5
    at req_ (C:\Users\nitin\Desktop\blur-admin-master\node_modules\natives\index.js:143:24)
    at Object.req [as require] (C:\Users\nitin\Desktop\blur-admin-master\node_modules\natives\index.js:55:10)
    at Object.<anonymous> (C:\Users\nitin\Desktop\blur-admin-master\node_modules\vinyl-fs\node_modules\graceful-fs\fs.js:1:37)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)

**Comment by zhangvqian** [comment]
I have got the same error : AssertionErroor [ERR_ASSERTION]: Task never defined:inject.
