### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by mkanker** [akveo/blur-admin#76]
I've just cloned, I ran the "npm install" and when I tried the "gulp server" I got this:

gulp serve
[14:50:37] Using gulpfile c:\Users\miche\Desktop\blur-admin\gulpfile.js
[14:50:37] Starting 'scripts'...
[14:50:37] Starting 'styles'...
[14:50:38] Starting 'stylesAuth'...
[14:50:38] Starting 'styles404'...
[14:50:38] Starting 'copyVendorImages'...
c:\Users\miche\Desktop\blur-admin\node_modules\gulp-eslint\node_modules\eslint\lib\config\config-file.js:332
            throw e;
            ^

Error: Cannot read config package: eslint-config-defaults/configurations/eslint
Error: Cannot find module 'eslint-config-defaults/configurations/eslint'
Referenced from: c:\Users\miche\.eslintrc
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at loadPackage (c:\Users\miche\Desktop\blur-admin\node_modules\gulp-eslint\node_modules\eslint\lib\config\config-file.js:168:16)
    at loadConfigFile (c:\Users\miche\Desktop\blur-admin\node_modules\gulp-eslint\node_modules\eslint\lib\config\config-file.js:212:18)
    at load (c:\Users\miche\Desktop\blur-admin\node_modules\gulp-eslint\node_modules\eslint\lib\config\config-file.js:385:18)
    at c:\Users\miche\Desktop\blur-admin\node_modules\gulp-eslint\node_modules\eslint\lib\config\config-file.js:326:36
    at Array.reduceRight (native)
    at applyExtends (c:\Users\miche\Desktop\blur-admin\node_modules\gulp-eslint\node_modules\eslint\lib\config\config-file.js:309:28)

**Comment by vazh** [comment]
what is your npm version, try updating it first, then delete node_modules folder, and bower_components folder.
then run `npm install` again

**Comment by mkanker** [comment]
3.9.6
I've tried in a clean installation

**Comment by ioudkerk** [comment]
is there any solution, i have windows 10 and the same problem

**Comment by ioudkerk** [comment]
I found how to fix. 

You can go to you user home, for example: c:\user\public and there delete all files with the extension .json and the .eslintrc file.

that fix my error.

**Comment by Cu4rach4** [comment]
#248
