### ISSUE TITLE
error runn gulp serve

### ISSUE THREAD

**Issue by k4ren** [akveo/blur-admin#90]
when I running gulp 

$ gulp serve
[11:53:13] Using gulpfile D:\app-admin\blur-admin\gulpfile.js
[11:53:13] Starting 'scripts'...
[11:53:14] Starting 'styles'...
[11:53:14] 'styles' errored after 116 ms
[11:53:14] Error: %1 no es una aplicación Win32 válida.
\?\D:\app-admin\blur-admin\node_modules\node-sass\vendor\win32-x64-47\binding.node
    at Error (native)
    at Object.Module._extensions..node (module.js:440:18)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (D:\app-admin\blur-admin\node_modules\node-sass\lib\index.js:24:15)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
[11:53:14] gulp-inject 50 files into main.scss.
[11:53:16] all files 241.53 kB
[11:53:16] Finished 'scripts' after 2.07 s

i use win 7 x64
any solution? :disappointed:

**Comment by k4ren** [comment]
solution :smile:
`npm install node-sass`

**Comment by vazh** [comment]
well, gulp-sass needs node-sass. it should be automatically installed as dependencies to gulp-sass.
probably because there's an error when running `npm install`

**Comment by k4ren** [comment]
closed :+1:
